admin:
  email: admin@admin.com
  password: admin
database:
  host: localhost
  port: 5432
  user: postgres
  password: artem2005
  database: game
bot:
  token: "7566227447:AAFDnW0FaxerLK2VvZn-XiDhyltkwbQE2kg"
jwt:
  access_tokem_expire_minutes: 360
  secret_key: secret_key
  algorithm: HS256